/**
 * sync-context — merges a product's two authored halves into the derived context that vendored
 * craft skills bind to.
 *
 *   PRD.md (frontmatter)  ─┐
 *                          ├─►  merge + derive aliases  ─►  validate  ─►  .factory/context.gen.yaml
 *   .factory/stack.yaml   ─┘
 *
 * Validation is real: the merged object is checked against project-context.schema.json with
 * Ajv. The previous version printed that claim in the generated file's header while only
 * regex-checking for two key names and copying the frontmatter through verbatim.
 *
 * Run inside a PRODUCT repo:  `fac sync-context`  (or `bun run sync-context`)
 * Optional arg: path to PRD.md (defaults to ./PRD.md).
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { join, relative } from 'node:path';
import { loadProductContext, checkOwnership, mergeContext, STACK_RELATIVE } from '../lib/context.ts';
import { validateContext } from '../lib/schema.ts';
import { stringifyYaml } from '../lib/yaml.ts';

function main() {
  const cwd = process.cwd();

  let ctx;
  try {
    ctx = loadProductContext(cwd, process.argv[2]);
  } catch (err) {
    console.error(`sync-context — ${(err as Error).message}`);
    process.exit(1);
  }

  const ownership = checkOwnership(ctx);
  if (ownership.length > 0) {
    console.error(
      'sync-context — ownership violations (PRD.md is human-owned; stack.yaml is machine-owned):',
    );
    for (const i of ownership) console.error(`  ✗ ${i.file}: ${i.message}`);
    process.exit(1);
  }

  const merged = mergeContext(ctx);

  const { ok, errors } = validateContext(merged);
  if (!ok) {
    console.error('sync-context — merged context fails project-context.schema.json:');
    for (const e of errors) console.error(`  ✗ ${e}`);
    process.exit(1);
  }

  const body = stringifyYaml(merged);

  const outDir = join(cwd, '.factory');
  mkdirSync(outDir, { recursive: true });
  const outPath = join(outDir, 'context.gen.yaml');
  const header =
    '# GENERATED by `fac sync-context` — DO NOT EDIT.\n' +
    `# Sources: PRD.md (frontmatter) + ${STACK_RELATIVE}\n` +
    '# Validated against project-context.schema.json. Edit a source file and re-run.\n' +
    "# 'project' and 'tech_bindings' are derived compatibility aliases for vendored craft skills.\n";
  writeFileSync(outPath, header + body);

  // Compatibility alias: vendored library skills reference `.agents/project-context.yaml` by
  // that literal path (e.g. fullstack-developer). Emit a byte-identical copy there so unmodified
  // library prose resolves without a fork. Same generated content; different well-known location.
  const agentsDir = join(cwd, '.agents');
  mkdirSync(agentsDir, { recursive: true });
  const aliasPath = join(agentsDir, 'project-context.yaml');
  const aliasHeader =
    '# GENERATED by `fac sync-context` — DO NOT EDIT.\n' +
    '# Compatibility alias of .factory/context.gen.yaml for vendored craft skills that\n' +
    '# reference `.agents/project-context.yaml` by that literal path. Edit a source file and re-run.\n';
  writeFileSync(aliasPath, aliasHeader + body);

  const note = Object.keys(ctx.stack).length === 0 ? '  (no stack.yaml yet — run /plan-arch)' : '';
  console.log(
    `sync-context — wrote ${relative(cwd, outPath)} + ${relative(cwd, aliasPath)}${note}`,
  );
}

if (import.meta.main) main();
